/**
 * LONER ASSISTANT v2.1 - Main Application Controller
 *
 * This is the app's single ES module entry point (loaded from index.html
 * via <script type="module">). It:
 * - Imports every other module (which wires up the dependency graph
 *   instead of relying on hand-ordered <script> tags)
 * - Runs application initialization
 * - Exposes a small, curated set of functions/namespaces on `window` so
 *   that inline onclick="..." handlers (in index.html and in HTML strings
 *   generated by the entity modules) keep working
 * - Handles theme switching and the service worker registration
 */

import { db } from './db/database.js';
import * as LonerDB from './db/database.js';
import * as UI from './ui.js';
import * as Editor from './editor.js';
import * as OracleSystem from './oracle.js';
import { TableSystem } from './tables.js';
import { TableManager } from './table-manager.js';
import { CustomTables } from './custom-tables.js';
import { ShortcutsSystem } from './shortcuts.js';
import { HelpSystem } from './onboarding.js';
import { ManualSystem } from './manual.js';
import { ExportImportSystem } from './export-import.js';
import { CampaignManager } from './campaigns.js';
import { CharacterManager } from './characters.js';
import { CharacterGenerator } from './character-generator.js';
import { NPCManager, showNPCPanel, showNewNPCForm } from './npcs.js';
import { LocationManager, showLocationPanel, showNewLocationForm } from './locations.js';
import { ThreadManager, showThreadPanel, showNewThreadForm } from './threads.js';
import { EventManager, showEventPanel } from './events.js';
import { SessionManager, showNewSessionForm, showSessionList, switchToSession, renameSession, deleteSessionConfirm } from './sessions.js';
import {
  getState,
  setCurrentCampaign,
  clearCurrentCampaign,
  setCurrentCharacter,
  clearCurrentCharacter,
  saveAppState,
  loadAppState
} from './state.js';

/**
 * Initialize the application when page loads
 */
document.addEventListener('DOMContentLoaded', async function () {
  console.log('🎲 Loner Assistant v2.1 starting...');

  try {
    // 1. Initialize UI first (doesn't need database)
    UI.initializeNavigation();
    loadThemePreference();
    console.log('✅ UI initialized');

    // 1a. Restore panel collapsed states
    UI.restorePanelStates();
    console.log('✅ Panel states restored');

    // 1b. Initialize toast notifications
    UI.showAlert; // (module is import-initialized; container is created lazily on first toast)
    console.log('✅ Notifications ready');

    // 2. Initialize editor (doesn't need database)
    Editor.initializeEditor();
    console.log('✅ Editor initialized');

    // 3. WAIT for database to be fully ready
    await db.open();
    console.log('✅ Database ready');

    // Initialize Tables System
    await TableSystem.init();
    console.log('✅ Table System initialized');

    // Initialize Custom Tables
    await CustomTables.init();
    console.log('✅ Custom Tables initialized');

    // Load random tables panel
    TableManager.showRandomTablesPanel();

    // 4. Give it a moment to settle
    await new Promise(resolve => setTimeout(resolve, 100));

    // 5. NOW load saved state
    const savedState = loadAppState();

    if (savedState && savedState.campaignId) {
      try {
        const campaign = await LonerDB.getCampaign(savedState.campaignId);
        if (campaign) {
          CampaignManager.displayCurrentCampaign(campaign);

          // Load session
          if (savedState.sessionId) {
            const session = await LonerDB.getSession(savedState.sessionId);
            if (session) {
              await Editor.loadSession(savedState.sessionId);
              SessionManager.displayCurrentSession(session);

              // Initialize Quick Links panels
              setTimeout(async () => {
                await showNPCPanel();
                await showLocationPanel();
                await showThreadPanel();
                await showEventPanel();
              }, 500);
            }
          }
        }
      } catch (error) {
        console.warn('Could not load saved state:', error);
        localStorage.removeItem('lonerAppState');
      }
    }

    // 6. Load active character
    try {
      const characters = await LonerDB.getCharacters();
      if (characters && characters.length > 0) {
        const activeChar = characters.find(c => c.isActive);
        if (activeChar) {
          setCurrentCharacter(activeChar.id);
          CharacterManager.displayActiveCharacter(activeChar);
        }
      }
    } catch (error) {
      console.warn('Could not load active character:', error);
    }

    // 7. Start auto-save
    Editor.startAutoSave();

    // 8. Initialize keyboard shortcuts
    ShortcutsSystem.init();
    console.log('✅ Keyboard shortcuts initialized');

    // 9. Initialize help system
    HelpSystem.init();
    console.log('✅ Help system initialized');

    // 10. Register the service worker (offline/PWA support)
    registerServiceWorker();

    console.log('✅ App initialized successfully!');

  } catch (error) {
    console.error('❌ Error initializing app:', error);
    UI.showAlert('App started with errors. Check console (F12).', 'error');
  }

  exposeCuratedGlobals();
});

/**
 * Theme switching
 */
function toggleTheme() {
  const body = document.body;
  const themeLabel = document.querySelector('.theme-label');

  if (body.classList.contains('ink-theme')) {
    body.classList.remove('ink-theme');
    themeLabel.textContent = 'Ink Theme';
    localStorage.setItem('theme', 'paper');
  } else {
    body.classList.add('ink-theme');
    themeLabel.textContent = 'Paper Theme';
    localStorage.setItem('theme', 'ink');
  }
}

function loadThemePreference() {
  const savedTheme = localStorage.getItem('theme');
  const themeLabel = document.querySelector('.theme-label');

  if (themeLabel) {
    if (savedTheme === 'ink' || savedTheme === 'dark') {
      document.body.classList.add('ink-theme');
      themeLabel.textContent = 'Paper Theme';
    } else {
      themeLabel.textContent = 'Ink Theme';
    }
  }
}

/**
 * Export menu toggle (Session Notes header dropdown)
 */
function toggleExportMenu(event) {
  event.stopPropagation();
  const menu = document.getElementById('export-menu');
  menu.style.display = menu.style.display === 'none' ? 'block' : 'none';
}

function hideExportMenu() {
  const menu = document.getElementById('export-menu');
  if (menu) menu.style.display = 'none';
}

// Close export menu when clicking outside
document.addEventListener('click', () => {
  hideExportMenu();
});

/**
 * Service worker registration
 */
function registerServiceWorker() {
  if (!('serviceWorker' in navigator)) return;

  navigator.serviceWorker.register('./sw.js').then(registration => {
    console.log('✅ Service worker registered');

    registration.addEventListener('updatefound', () => {
      const newWorker = registration.installing;
      if (!newWorker) return;
      newWorker.addEventListener('statechange', () => {
        if (newWorker.state === 'installed' && navigator.serviceWorker.controller) {
          UI.showAlert('A new version is available. Reload to update.', 'info', 8000);
        }
      });
    });
  }).catch(error => {
    console.warn('Service worker registration failed:', error);
  });
}

/**
 * Expose a small, deliberately-curated set of functions/namespaces on
 * `window` - this is what makes the inline onclick="..." handlers in
 * index.html and in HTML strings generated by the entity modules work,
 * since those strings can't reach module-scoped bindings directly.
 */
function exposeCuratedGlobals() {
  // Namespace objects referenced as Object.method(...) in markup
  window.UI = UI;
  window.Editor = Editor;
  window.OracleSystem = OracleSystem;
  window.TableSystem = TableSystem;
  window.TableManager = TableManager;
  window.CustomTables = CustomTables;
  window.ShortcutsSystem = ShortcutsSystem;
  window.HelpSystem = HelpSystem;
  window.ManualSystem = ManualSystem;
  window.ExportImportSystem = ExportImportSystem;
  window.CampaignManager = CampaignManager;
  window.CharacterManager = CharacterManager;
  window.CharacterGenerator = CharacterGenerator;
  window.NPCManager = NPCManager;
  window.LocationManager = LocationManager;
  window.ThreadManager = ThreadManager;
  window.EventManager = EventManager;
  window.SessionManager = SessionManager;

  // Bare function names referenced directly in markup
  window.showView = UI.showView;
  window.closeModal = UI.closeModal;
  window.toggleNavMenu = UI.toggleNavMenu;
  window.toggleTheme = toggleTheme;
  window.toggleExportMenu = toggleExportMenu;
  window.hideExportMenu = hideExportMenu;
  window.saveNotes = Editor.saveNotes;

  window.rollOracle = OracleSystem.rollOracle;
  window.rollScene = OracleSystem.rollScene;
  window.resetTwistCounter = OracleSystem.resetTwistCounter;
  window.triggerTwist = OracleSystem.triggerTwist;
  window.startConflict = OracleSystem.startConflict;
  window.rollConflict = OracleSystem.rollConflict;
  window.endConflict = OracleSystem.endConflict;

  // Per-view list loaders - showView()'s dispatch in ui.js calls these by
  // bare name (window.loadXList) when switching to that view.
  window.loadCampaignsList = CampaignManager.loadCampaignsList;
  window.loadCharactersList = CharacterManager.loadCharactersList;
  window.loadNPCsList = NPCManager.loadNPCsList;
  window.loadLocationsList = LocationManager.loadLocationsList;
  window.loadThreadsList = ThreadManager.loadThreadsList;
  window.loadEventTimeline = EventManager.loadEventTimeline;

  window.showNewCampaignForm = CampaignManager.showNewCampaignForm;
  window.showNewCharacterForm = CharacterManager.showNewCharacterForm;
  window.viewCharacterSheet = CharacterManager.viewCharacterSheet;
  window.editCharacter = CharacterManager.editCharacter;
  window.setAsActiveCharacter = CharacterManager.setAsActiveCharacter;
  window.deleteCharacterConfirm = CharacterManager.deleteCharacterConfirm;

  window.showNewNPCForm = showNewNPCForm;
  window.viewNPCDetails = NPCManager.viewNPCDetails;
  window.editNPC = NPCManager.editNPC;
  window.deleteNPCConfirm = NPCManager.deleteNPCConfirm;

  window.showNewLocationForm = showNewLocationForm;
  window.viewLocationDetails = LocationManager.viewLocationDetails;
  window.markLocationVisited = LocationManager.markLocationVisited;
  window.markLocationVisitedAndClose = LocationManager.markLocationVisitedAndClose;
  window.editLocation = LocationManager.editLocation;
  window.deleteLocationConfirm = LocationManager.deleteLocationConfirm;

  window.showNewThreadForm = showNewThreadForm;
  window.viewThreadDetails = ThreadManager.viewThreadDetails;
  window.resolveThreadAndClose = ThreadManager.resolveThreadAndClose;
  window.editThread = ThreadManager.editThread;
  window.deleteThreadConfirm = ThreadManager.deleteThreadConfirm;

  window.showNewEventForm = EventManager.showNewEventForm;
  window.deleteEventConfirm = EventManager.deleteEventConfirm;

  window.showSessionList = showSessionList;
  window.showNewSessionForm = showNewSessionForm;
  window.switchToSession = switchToSession;
  window.renameSession = renameSession;
  window.deleteSessionConfirm = deleteSessionConfirm;
}

// Export App interface (used by other modules via `window.App` where a
// static import isn't wired, and available for console debugging)
window.App = {
  getState,
  setCurrentCampaign,
  clearCurrentCampaign,
  setCurrentCharacter,
  clearCurrentCharacter,
  saveAppState,
  loadAppState
};

// Debug helper
window.LonerDebug = {
  getCurrentState: () => ({
    ...getState(),
    hasEditor: !!Editor.getEditor(),
    dbVersion: db.verno
  }),
  getCampaigns: () => LonerDB.getAllCampaigns(),
  getSessions: (campaignId) => LonerDB.getSessionsForCampaign(campaignId || getState().campaignId),
  getCharacters: () => LonerDB.getCharacters(),
  testSave: () => Editor.saveNotes(),
  saveState: () => saveAppState(),
  loadState: () => loadAppState(),
  clearState: () => {
    localStorage.removeItem('lonerAppState');
    console.log('✅ State cleared');
  },
  clearAll: async () => {
    if (confirm('This will DELETE ALL DATA. Are you sure?')) {
      localStorage.clear();
      await db.delete();
      console.log('✅ All data cleared. Refreshing...');
      location.reload();
    }
  }
};

console.log('💡 Debug tools available:');
console.log('  LonerDebug.getCurrentState() - Check app state');
console.log('  LonerDebug.clearAll() - Delete everything and start fresh');
console.log('  LonerDebug.clearState() - Clear saved state only');
